name: full_example
description: An example project that demonstrates all Widgetbook features.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  widgetbook:
    path: ../../packages/widgetbook
  widgetbook_annotation:
    path: ../../packages/widgetbook_annotation

dev_dependencies:
  build_runner: ^2.4.11
  widgetbook_generator:
    path: ../../packages/widgetbook_generator

flutter:
  uses-material-design: true
