name: widgetbook_generator
description: A package to automate setup and maintenance of the widgetbook package by using code generation.
version: 3.8.0
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_generator
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]
publish_to: none

screenshots:
  - description: "Widgetbook Logo"
    path: assets/logo.png

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: ">=5.10.0 <7.0.0"
  build: ^2.1.0
  code_builder: ^4.5.0
  collection: ^1.15.0
  crypto: ^3.0.0
  dart_style: ^2.3.0
  glob: ^2.0.2
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^1.1.0
  widgetbook:
    path: ../widgetbook
  widgetbook_annotation:
    path: ../widgetbook_annotation
  yaml: ^3.1.1

dev_dependencies:
  test: ^1.21.0
